#!/bin/bash

set -euo pipefail

project_path="$(dirname $0)/.."

cat "${project_path}/cilium/values.yaml" | envsubst '${INFRA_LB_IP}' > /tmp/cilium-values.yaml

helm upgrade --install cilium oci://quay.io/cilium/charts/cilium --version 1.19.1 \
  --namespace network \
  --create-namespace \
  --values /tmp/cilium-values.yaml > /dev/null

kubectl wait --namespace network \
  --for=create daemonset.apps/cilium-envoy \
  --timeout=300s

kubectl wait --namespace network \
  --for=condition=Ready pod \
  --selector=name=cilium-envoy \
  --timeout=300s

kubectl wait --namespace network \
  --for=create daemonset.apps/cilium \
  --timeout=300s

kubectl wait --namespace network \
  --for=condition=Ready pod \
  --selector=app.kubernetes.io/name=cilium-agent \
  --timeout=300s

kubectl kustomize --enable-helm "${project_path}/cilium" | envsubst '${INFRA_DOMAIN} ${INFRA_LB_IP} ${INFRA_HA_VIP}' | kubectl apply --server-side -f - > /dev/null
