#!/bin/bash

set -eu

project_path="$(dirname $0)/.."

# Install ESO CRDs
kubectl apply -f "https://raw.githubusercontent.com/external-secrets/external-secrets/v2.0.0/deploy/crds/bundle.yaml" --server-side

kubectl create namespace external-secrets || true

# Install ESO
kubectl kustomize "${project_path}/external-secrets" --enable-helm | kubectl apply --wait -f -

kubectl --namespace external-secrets wait --for condition=available deploy/external-secrets-webhook
