#!/bin/bash

set -euo pipefail

project_path="$(dirname $0)/.."

# Add helm repository
helm repo add longhorn https://charts.longhorn.io > /dev/null && \
  helm repo update > /dev/null

cat "${project_path}/longhorn-system/values.yaml" | envsubst '${INFRA_ENV}' > /tmp/longhorn-system-values.yaml

helm upgrade --install longhorn longhorn/longhorn --version 1.11.0 \
  --namespace longhorn-system \
  --create-namespace \
  --values "/tmp/longhorn-system-values.yaml" > /dev/null

kubectl wait --namespace longhorn-system \
  --for=create daemonset/longhorn-csi-plugin \
  --timeout=300s

kubectl wait --namespace longhorn-system \
  --for=condition=Ready pod \
  --selector=app=longhorn-csi-plugin \
  --timeout=300s

until kubectl get storageclass longhorn >/dev/null 2>&1; do
  echo "Waiting for 'longhorn' StorageClass to be created..."
  sleep 5
done
