#!/bin/bash

set -euo pipefail

project_path="$(dirname $0)/.."

kubectl create namespace longhorn-system 2>/dev/null || true

kubectl kustomize --enable-helm "${project_path}/longhorn-system" | envsubst '${INFRA_DOMAIN}' | kubectl apply --server-side -f - > /dev/null

kubectl wait --namespace longhorn-system \
  --for=create daemonset/longhorn-csi-plugin \
  --timeout=300s

kubectl wait --namespace longhorn-system \
  --for=condition=Ready pod \
  --selector=app=longhorn-csi-plugin \
  --timeout=300s

until kubectl get storageclass longhorn >/dev/null 2>&1; do
  echo "Waiting for 'longhorn' StorageClass to be created..."
  sleep 5
done
