apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: gateway-client-external-secret
spec:
  refreshPolicy: OnChange
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: gateway-client-secret
  data:
  - secretKey: client-secret
    remoteRef:
      key: /sec/keycloak
      property: clientSecret
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: gateway-client-external-secret
  namespace: devops-tools
spec:
  refreshPolicy: OnChange
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: gateway-client-secret
  data:
  - secretKey: client-secret
    remoteRef:
      key: /sec/keycloak
      property: clientSecret
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: gateway-client-external-secret
  namespace: monitoring
spec:
  refreshPolicy: OnChange
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: gateway-client-secret
  data:
  - secretKey: client-secret
    remoteRef:
      key: /sec/keycloak
      property: clientSecret
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: gateway-client-external-secret
  namespace: media
spec:
  refreshPolicy: OnChange
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: gateway-client-secret
  data:
  - secretKey: client-secret
    remoteRef:
      key: /sec/keycloak
      property: clientSecret
