apiVersion: gateway.envoyproxy.io/v1alpha1
kind: SecurityPolicy
metadata:
  name: keycloak-oidc
spec:
  targetRefs:
  - group: gateway.networking.k8s.io
    kind: Gateway
    name: cluster-gateway
  oidc:
    provider:
      issuer: "http://keycloak-keycloakx-http.sec.svc.cluster.local:9000/auth/realms/test"
    clientID: test
    clientSecret:
      name: client-secret
    logoutPath: "/logout"
