apiVersion: gateway.envoyproxy.io/v1alpha1
kind: ClientTrafficPolicy
metadata:
  name: oauth2-proxy-traffic-policy
spec:
  headers:
    earlyRequestHeaders:
      set:
      - name: X-Auth-Request-Redirect
        value: https://%REQ(Host)%%REQ(:PATH)%
  targetRef:
    group: gateway.networking.k8s.io
    kind: Gateway
    name: cluster-gateway
---
apiVersion: gateway.envoyproxy.io/v1alpha1
kind: SecurityPolicy
metadata:
  name: devops-tools-security-policy
  namespace: devops-tools
spec:
  targetRefs:
  - group: gateway.networking.k8s.io
    kind: HTTPRoute
    name: argocd-route
  extAuth:
    headersToExtAuth:
    - Cookie
    - X-Auth-Request-User
    - X-Auth-Request-Groups
    - X-Auth-Request-Email
    - X-Auth-Request-Preferred-Username
    - X-Forwarded-Proto
    - X-Forwarded-Host
    - X-Forwarded-Uri
    - X-Auth-Request-Access-Token
    - X-Auth-Request-Redirect
    http:
      backendRefs:
      - group: ""
        kind: Service
        name: oauth2-proxy
        namespace: sec
        port: 80
        weight: 1
      path: /oauth2/auth
---
apiVersion: gateway.envoyproxy.io/v1alpha1
kind: SecurityPolicy
metadata:
  name: longhorn-security-policy
  namespace: longhorn-system
spec:
  targetRefs:
  - group: gateway.networking.k8s.io
    kind: HTTPRoute
    name: longhorn-route
  extAuth:
    headersToExtAuth:
    - Cookie
    - X-Auth-Request-User
    - X-Auth-Request-Groups
    - X-Auth-Request-Email
    - X-Auth-Request-Preferred-Username
    - X-Forwarded-Proto
    - X-Forwarded-Host
    - X-Forwarded-Uri
    - X-Auth-Request-Access-Token
    - X-Auth-Request-Redirect
    http:
      backendRefs:
      - group: ""
        kind: Service
        name: oauth2-proxy
        namespace: sec
        port: 80
        weight: 1
      path: /oauth2/auth
---
apiVersion: gateway.envoyproxy.io/v1alpha1
kind: SecurityPolicy
metadata:
  name: media-security-policy
  namespace: media
spec:
  targetRefs:
  - group: gateway.networking.k8s.io
    kind: HTTPRoute
    name: cwa-route
  - group: gateway.networking.k8s.io
    kind: HTTPRoute
    name: hometube-route
  - group: gateway.networking.k8s.io
    kind: HTTPRoute
    name: jellyfin-route
  - group: gateway.networking.k8s.io
    kind: HTTPRoute
    name: yubal-route
  extAuth:
    headersToExtAuth:
    - Cookie
    - X-Auth-Request-User
    - X-Auth-Request-Groups
    - X-Auth-Request-Email
    - X-Auth-Request-Preferred-Username
    - X-Forwarded-Proto
    - X-Forwarded-Host
    - X-Forwarded-Uri
    - X-Auth-Request-Access-Token
    - X-Auth-Request-Redirect
    http:
      backendRefs:
      - group: ""
        kind: Service
        name: oauth2-proxy
        namespace: sec
        port: 80
        weight: 1
      path: /oauth2/auth
---
apiVersion: gateway.envoyproxy.io/v1alpha1
kind: SecurityPolicy
metadata:
  name: monitoring-security-policy
  namespace: monitoring
spec:
  targetRefs:
  - group: gateway.networking.k8s.io
    kind: HTTPRoute
    name: grafana-route
  - group: gateway.networking.k8s.io
    kind: HTTPRoute
    name: prometheus-route
  extAuth:
    headersToExtAuth:
    - Cookie
    - X-Auth-Request-User
    - X-Auth-Request-Groups
    - X-Auth-Request-Email
    - X-Auth-Request-Preferred-Username
    - X-Forwarded-Proto
    - X-Forwarded-Host
    - X-Forwarded-Uri
    - X-Auth-Request-Access-Token
    - X-Auth-Request-Redirect
    http:
      backendRefs:
      - group: ""
        kind: Service
        name: oauth2-proxy
        namespace: sec
        port: 80
        weight: 1
      path: /oauth2/auth
---
apiVersion: gateway.envoyproxy.io/v1alpha1
kind: SecurityPolicy
metadata:
  name: network-security-policy
  namespace: network
spec:
  targetRefs:
  - group: gateway.networking.k8s.io
    kind: HTTPRoute
    name: hubble-route
  extAuth:
    headersToExtAuth:
    - Cookie
    - X-Auth-Request-User
    - X-Auth-Request-Groups
    - X-Auth-Request-Email
    - X-Auth-Request-Preferred-Username
    - X-Forwarded-Proto
    - X-Forwarded-Host
    - X-Forwarded-Uri
    - X-Auth-Request-Access-Token
    - X-Auth-Request-Redirect
    http:
      backendRefs:
      - group: ""
        kind: Service
        name: oauth2-proxy
        namespace: sec
        port: 80
        weight: 1
      path: /oauth2/auth
---
apiVersion: gateway.envoyproxy.io/v1alpha1
kind: SecurityPolicy
metadata:
  name: p2p-security-policy
  namespace: p2p
spec:
  targetRefs:
  - group: gateway.networking.k8s.io
    kind: HTTPRoute
    name: jackett-route
  - group: gateway.networking.k8s.io
    kind: HTTPRoute
    name: qb-route
  - group: gateway.networking.k8s.io
    kind: HTTPRoute
    name: slskd-route
  extAuth:
    headersToExtAuth:
    - Cookie
    - X-Forwarded-Proto
    - X-Forwarded-Host
    - X-Auth-Request-Redirect
    http:
      backendRefs:
      - group: ""
        kind: Service
        name: oauth2-proxy
        namespace: sec
        port: 80
        weight: 1
      path: /oauth2/auth
