apiVersion: gateway.envoyproxy.io/v1alpha1
kind: SecurityPolicy
metadata:
  name: keycloak-oidc
spec:
  targetRefs:
  #- group: gateway.networking.k8s.io
  #  kind: Gateway
  #  name: cluster-gateway
  - group: gateway.networking.k8s.io
    kind: HTTPRoute
    name: hubble-route
  oidc:
    provider:
      issuer: "http://keycloak-keycloakx-http.sec.svc.cluster.local/auth/realms/test"
    clientID: test
    clientSecret:
      name: client-secret
    logoutPath: "/logout"
