apiVersion: gateway.envoyproxy.io/v1alpha1
kind: SecurityPolicy
metadata:
  name: keycloak-oidc
spec:
  targetRefs:
  - group: gateway.networking.k8s.io
    kind: Gateway
    name: cluster-gateway
  oidc:
    provider:
      issuer: "http://keycloak.sec.svc.cluster.local/auth/realms/test"
    clientID: test
    clientSecret:
      name: client-secret
    logoutPath: "/logout"
