apiVersion: gateway.envoyproxy.io/v1alpha1
kind: SecurityPolicy
metadata:
  name: admin-security-policy
spec:
  targetRefs:
  - group: gateway.networking.k8s.io
    kind: HTTPRoute
    name: hubble-route
  oidc:
    provider:
      issuer: https://keycloak.${INFRA_DOMAIN}/auth/realms/cluster
    clientID: gateway
    clientSecret:
      name: gateway-client-secret
    logoutPath: "/logout"
  authorization:
    defaultAction: Deny
    rules:
    - name: "allow-admin-role"
      action: Allow
      principal:
        jwt:
          provider: keycloak
          claims:
          - name: roles
            valueType: "StringArray"
            values:
            - "admin"
  jwt:
    providers:
    - name: keycloak
      issuer: https://keycloak.${INFRA_DOMAIN}/auth/realms/cluster
      remoteJWKS:
        cacheDuration: 300s
        uri: https://keycloak.${INFRA_DOMAIN}/auth/realms/cluster/protocol/openid-connect/certs
      extractFrom:
        cookies:
        - "AccessToken-c8595934"
---
apiVersion: gateway.envoyproxy.io/v1alpha1
kind: SecurityPolicy
metadata:
  name: media-security-policy
spec:
  targetRefs:
  - group: gateway.networking.k8s.io
    kind: HTTPRoute
    name: jellyfin-route
  oidc:
    provider:
      issuer: https://keycloak.${INFRA_DOMAIN}/auth/realms/cluster
    clientID: gateway
    clientSecret:
      name: gateway-client-secret
    logoutPath: "/logout"
  authorization:
    defaultAction: Deny
    rules:
    - name: "allow-admin-and-media-roles"
      action: Allow
      principal:
        jwt:
          provider: keycloak
          claims:
          - name: roles
            valueType: "StringArray"
            values:
            - "admin"
            - "media"
  jwt:
    providers:
    - name: keycloak
      issuer: https://keycloak.${INFRA_DOMAIN}/auth/realms/cluster
      remoteJWKS:
        cacheDuration: 300s
        uri: https://keycloak.${INFRA_DOMAIN}/auth/realms/cluster/protocol/openid-connect/certs
