apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: crds
  namespace: devops-tools
  annotations:
    argocd.argoproj.io/sync-wave: "-5"
spec:
  destination:
    server: https://kubernetes.default.svc
  project: default
  source:
    path: ./crds
    repoURL: https://github.com/msdeleyto/homelab-manifests.git
    targetRevision: main
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - ServerSideApply=true
