apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: dex-config-external-secret
spec:
  refreshPolicy: OnChange
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: dex-config
    template:
      data:
        config.yaml: |
          issuer: http://localhost:8080/dex

          storage:
            type: memory

          staticPasswords:
          - email: "{{ .user1Email }}"
            hash: "{{ .user1Password }}"
            username: "{{ .user1Name }}"
            userID: "aae58fb8-2ccc-4da9-955e-9037e1a6c3fa"

          enablePasswordDB: true

          oauth2:
            passwordConnector: local
  data:
  - secretKey: user1Email
    remoteRef:
      key: /sec/dex
      property: user1Email
  - secretKey: user1Name
    remoteRef:
      key: /sec/dex
      property: user1Name
  - secretKey: user1Password
    remoteRef:
      key: /sec/dex
      property: user1Password
