apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: vault-unsealer-keys-external-secret
  namespace: vault
spec:
  refreshPolicy: OnChange
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: vault-unsealer-keys
  data:
  - secretKey: KEY1
    remoteRef:
      key: /vault/unsealer
      property: key1
  - secretKey: KEY2
    remoteRef:
      key: /vault/unsealer
      property: key2
  - secretKey: KEY3
    remoteRef:
      key: /vault/unsealer
      property: key3
