apiVersion: v1
kind: ConfigMap
metadata:
  name: yubal-router-nginx
data:
  default.conf: |
    server {
      listen 8080;
      server_name _;

      location = /healthz {
        return 200;
      }

      location / {
        set $auth_user $http_x_auth_request_user;

        if ($auth_user = "ari") {
          proxy_pass http://yubal-ari:8000;
          break;
        }

        if ($auth_user = "miguel") {
          proxy_pass http://yubal-miguel:8000;
          break;
        }

        return 403;
      }
    }
