apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: media

helmGlobals:
  chartHome: ../../charts

helmCharts:
- name: base-app
  releaseName: yubal-router
  valuesFile: values-router.yaml

- name: base-app
  releaseName: yubal
  valuesFile: values.yaml
  additionalValuesFiles:
  - values-ari.yaml

- name: base-app
  releaseName: yubal
  valuesFile: values.yaml
  additionalValuesFiles:
  - values-miguel.yaml

resources:
- config-map.yaml
- pvc.yaml
- http-route.yaml
