pvc:
  storageClassName: longhorn
  accessModes:
  - ReadWriteOnce
  size: 1Gi

qbittorrent:
  image:
    repository: msd117/qbittorrent
    tag: 0.0.7@sha256:391fd2438754906b67eaf30bfd94b11e232e712337a2f0c0c917f7a4c39c165a

vpn:
  image:
    repository: qmcgaw/gluetun
    tag: v3.41.1
