pvc:
  storageClassName: longhorn
  accessModes:
  - ReadWriteOnce
  size: 1Gi

qbittorrent:
  image:
    repository: msd117/qbittorrent
    tag: 0.0.7

vpn:
  image:
    repository: qmcgaw/gluetun
    tag: v3.41.1
