#!/bin/bash

set -eu

project_path="$(git rev-parse --show-toplevel)"

# nfs
echo -e "\nDeploying nfs..."
nfs_dir="${project_path}/storage/nfs"

# Replace secrets
sed -i "s|<path:secret/data/infra#k8s_nfs>|${K8S_NFS}|" "${nfs_dir}"/values.yaml

helm upgrade --install --namespace storage --create-namespace -f "${nfs_dir}"/values.yaml nfs-sc "${nfs_dir}"
