#!/bin/bash

set -euo pipefail

## File format:
# ---
# namespace:
#   app:
#     secret1: file_path
secrets_file_path="${1}"

if [ ! -f "${secrets_file_path}" ]; then
  echo "YAML file not found: ${secrets_file_path}"
  exit 1
fi

path_to_secrets="$(realpath "$(dirname "${secrets_file_path}")")"

if ! command -v yq &> /dev/null; then
  echo "yq is required but not found"
  exit 1
fi

namespaces="$(yq -r 'keys[]' ${secrets_file_path})"

for namespace in ${namespaces}; do
    apps="$(yq -r ".${namespace} | keys[]" "${secrets_file_path}")"
    for app in ${apps}; do
        secrets="$(yq -r ".${namespace}.${app}" "${secrets_file_path}" | yq -r 'to_entries[] | "\(.key)=\(.value)"')"
        for secret in ${secrets}; do
            key="$(echo ${secret} | cut -d '=' -f1)"
            file_path="$(echo ${secret} | cut -d '=' -f2)"
            kubectl -n vault exec -it vault-0 -- vault kv put secret/${namespace}/${app}/${key} private_key="$(< ${path_to_secrets}/${file_path})"
        done
    done
done
