#!/bin/bash

set -euo pipefail

## File format:
# ---
# namespace:
#   app:
#     secret1: file_path
secret_files="${1}"

if ! command -v yq &> /dev/null; then
  echo "yq is required but not found"
  exit 1
fi

namespaces="$(echo "${secret_files}" | yq -r 'keys[]')"

for namespace in ${namespaces}; do
    apps="$(echo "${secret_files}" | yq -r ".${namespace} | keys[]")"
    for app in ${apps}; do
        secrets="$(echo "${secret_files}" | yq -r ".${namespace}.${app}" | yq -r 'to_entries[] | "\(.key)=\(.value)"')"
        for secret in ${secrets}; do
            key="$(echo ${secret} | cut -d '=' -f1)"
            file_path="$(echo ${secret} | cut -d '=' -f2)"
            echo "Loading content of: ${file_path}"
            kubectl -n vault exec vault-0 -- vault kv put secret/${namespace}/${app}/${key} private_key="$(< ${file_path})"
        done
    done
done
