#!/bin/bash

set -euo pipefail

## File format:
# ---
# namespace:
#   app:
#     secret1: value1
#     secret2: value2
secrets="${1}"

if ! command -v yq &> /dev/null; then
  echo "yq is required but not found"
  exit 1
fi

namespaces="$(echo ${secrets} | yq -r 'keys[]')"

for namespace in ${namespaces}; do
    if [[ "${namespace}" == "infra" ]]; then
        infra_secrets="$(echo ${secrets} | yq -r ".${namespace}" | yq -r 'to_entries[] | "\(.key)=\(.value)"')"
        infra_secrets="$(echo ${infra_secrets} | tr '\n' ' ')"
        echo "Storing secrets: ${infra_secrets}"
        # kubectl -n vault exec vault-0 -- vault kv put secret/"${namespace}" ${infra_secrets}
    else
        apps="$(echo ${secret_files} | yq -r ".${namespace} | keys[]")"
        for app in ${apps}; do
            app_secrets="$(echo ${secrets} | yq -r ".${namespace}.${app}" | yq -r 'to_entries[] | "\(.key)=\(.value)"')"
            app_secrets="$(echo ${app_secrets} | tr '\n' ' ')"
            echo "Storing secrets: ${sapp_secretss}"
            # kubectl -n vault exec vault-0 -- vault kv put secret/"${namespace}"/"${app}" ${app_secrets}
        done
    fi
done
