apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: shelfmark-vpn-external-secret
spec:
  refreshPolicy: OnChange
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: shelfmark-vpn-secret
  data:
  - secretKey: WIREGUARD_PRIVATE_KEY
    remoteRef:
      key: /p2p/vpn
      property: wireguard_private_key
