apiVersion: longhorn.io/v1beta2
kind: RecurringJob
metadata:
  name: snapshot
  namespace: longhorn-system
spec:
  cron: "0 20 * * *"
  task: "snapshot"
  groups:
  - default
  retain: 1
  concurrency: 2
