apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: qbittorrent-external-secret
  namespace: p2p
spec:
  refreshPolicy: OnChange
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: qbittorrent-secret
  data:
  - secretKey: WEB_UI_PASSWORD
    remoteRef:
      key: /p2p/qbittorrent
      property: webuiPassword
  - secretKey: QBT_API_PASSWORD
    remoteRef:
      key: /p2p/qbittorrent
      property: apiPassword
  - secretKey: DEST_EMAIL_ADDRESS
    remoteRef:
      key: /p2p/scan
      property: destEmailAddress
  - secretKey: ORIGIN_EMAIL_AUTHUSER
    remoteRef:
      key: /p2p/scan
      property: originEmailAuthUser
  - secretKey: ORIGIN_EMAIL_AUTH_PASS
    remoteRef:
      key: /p2p/scan
      property: originEmailAuthPass
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: qbittorrent-vpn-external-secret
  namespace: p2p
spec:
  refreshPolicy: OnChange
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: qbittorrent-vpn-secret
  data:
  - secretKey: WIREGUARD_PRIVATE_KEY
    remoteRef:
      key: /p2p/vpn
      property: wireguard_private_key
