apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: qbittorrent-external-secret
spec:
  refreshPolicy: OnChange
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: qbittorrent-secret
  data:
  - secretKey: QBT_API_PASSWORD
    remoteRef:
      key: /p2p/qbittorrent
      property: apiPassword
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: qbittorrent-vpn-external-secret
spec:
  refreshPolicy: OnChange
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: qbittorrent-vpn-secret
  data:
  - secretKey: WIREGUARD_PRIVATE_KEY
    remoteRef:
      key: /p2p/vpn
      property: wireguard_private_key
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: qbittorrent-config-external-secret
spec:
  refreshPolicy: OnChange
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: qbittorrent-config
    manifest:
      apiVersion: v1
      kind: ConfigMap
    template:
      data:
        qBittorrent.conf: |
          [BitTorrent]
          Session\DefaultSavePath=/downloads/complete
          Session\Port=6881
          Session\TempPath=/downloads/incomplete
          Session\TempPathEnabled=true

          [AutoRun]
          enabled=true
          program=/scan_file {{ "{{ .destEmailAddress }}" }} /quarantine /var/log/cerberus %F

          [Preferences]
          WebUI\Password_PBKDF2="@ByteArray({{ "{{ .webuiPassword }}" }})"
  data:
  - secretKey: webuiPassword
    remoteRef:
      key: /p2p/qbittorrent
      property: webuiPassword
  - secretKey: destEmailAddress
    remoteRef:
      key: /p2p/scan
      property: destEmailAddress
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: qbittorrent-ssmtp-config-external-secret
spec:
  refreshPolicy: OnChange
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: qbittorrent-ssmtp-config
    manifest:
      apiVersion: v1
      kind: ConfigMap
    template:
      data:
        ssmtp.conf: |
          root=postmaster
          SERVER={{ "{{ .originEmailAuthUser }}" }}

          mailhub=smtp.gmail.com:587
          AuthUser={{ "{{ .originEmailAuthUser }}" }}
          Authpass={{ "{{ .originEmailAuthPass }}" }}
          UseTLS=YES
          UseSTARTTLS=YES

          FromLineOverride=YES
  data:
  - secretKey: originEmailAuthUser
    remoteRef:
      key: /p2p/scan
      property: originEmailAuthUser
  - secretKey: originEmailAuthPass
    remoteRef:
      key: /p2p/scan
      property: originEmailAuthPass
