apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: domain
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/managed-by: Helm
  annotations:
    meta.helm.sh/release-name: {{ .Release.Name }}
    meta.helm.sh/release-namespace: {{ .Release.Namespace }}
spec:
  secretName: domain-tls-secret
  commonName: {{ .Values.rootDomain }}
  issuerRef:
    name: letsencrypt-{{ .Values.env }}
    kind: ClusterIssuer
  dnsNames:
  - {{ .Values.rootDomain }}
  - "*.{{ .Values.rootDomain }}"
  secretTemplate:
    annotations:
      replicator.v1.mittwald.de/replication-allowed: "true"
      replicator.v1.mittwald.de/replication-allowed-namespaces: "*"
      replicator.v1.mittwald.de/replicate-to: "*"
