apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: media

helmGlobals:
  chartHome: ../../charts

helmCharts:
- name: base-app
  valuesFile: values.yaml

resources:
- pvc.yaml
- cronjob.yaml
- network-policy.yaml
