pvc:
  storageClassName: longhorn
  accessModes:
  - ReadWriteOnce
  size: 10Gi

deployment:
  image:
    repository: docker.io/jellyfin/jellyfin
    tag: "10.11.9@sha256:bc9fa8e1462fffe3d8d4255fc62af478602641f4c0e5f4875fea8563d1189837"

backup:
  schedule: "0 15 * * *"
  image:
    repository: busybox
    tag: "1.38@sha256:fd8d9aa63ba2f0982b5304e1ee8d3b90a210bc1ffb5314d980eb6962f1a9715d"
  command: |
    echo "Starting backup at $(date)"
    tar -czf /backup/jellyfin-$(date +%Y%m%d%H%M%S).tar.gz /config
    echo "Backup completed at $(date)"
    echo "Removing backups older than 3 days"
    find /backup -maxdepth 1 -mtime +3 -type f -delete
