#!/bin/bash

set -euo pipefail

# Add helm repository for argocd
helm repo add argo https://argoproj.github.io/argo-helm && \
  helm repo update

# Install CRDs
kubectl apply --server-side -k https://github.com/argoproj/argo-cd/manifests/crds\?ref\=stable

kubectl create namespace devops-tools || true

project_path="$(dirname $0)/.."
argocd_dir="${project_path}/argocd"

kubectl apply -f "${argocd_dir}/external-secrets.yaml" --wait

# Deploy only once to not replace vars on it
# kubectl apply -f "${argocd_dir}/envusbst-plugin.yaml"

kubectl kustomize --enable-helm "${argocd_dir}" | envsubst '${INFRA_DOMAIN} ${INFRA_ENV}' | kubectl apply --wait -f - > /dev/null

echo -e "Done!\n"
