apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: oauth2-proxy-external-secret
spec:
  refreshPolicy: OnChange
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: oauth2-proxy-secret
  data:
  - secretKey: OAUTH2_PROXY_COOKIE_SECRET
    remoteRef:
      key: /sec/oauth2proxy
      property: cookieSecret
  - secretKey: OAUTH2_PROXY_CLIENT_SECRET
    remoteRef:
      key: /sec/keycloak
      property: clientSecret
