apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: oauth2-proxy-config-external-secret
spec:
  refreshPolicy: OnChange
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: oauth2-proxy-config
    manifest:
      apiVersion: v1
      kind: ConfigMap
    template:
      data:
        oauth2_proxy.yml: |
          server:
            cookie:
              secret: "{{ .cookieSecret }}"
              domains: [".${INFRA_DOMAIN}"]
              httpOnly: false
              secure: true

          upstreamConfig:
            upstreams:
            - id: static-200
              uri: static://200

          providers:
          - id: keycloak
            provider: oidc
            clientID: "oauth2-proxy"
            clientSecret: "{{ .clientSecret }}"
            oidcConfig:
              issuerURL: "https://keycloak.${INFRA_DOMAIN}/auth/realms/cluster"
              emailDomains: ["*"]
              codeChallengeMethod: S256
              userIDClaim: "username"
            redirectURL: "https://oauth2-proxy.${INFRA_DOMAIN}/oauth2/callback"

          injectRequestHeaders:
          - name: X-Auth-Request-User
            values:
            - claimSource:
                claim: username
          - name: X-Auth-Request-Email
            values:
            - claimSource:
                claim: email
          - name: X-Auth-Request-Roles
            values:
            - claimSource:
                claim: roles
  data:
  - secretKey: clientSecret
    remoteRef:
      key: /sec/keycloak
      property: clientSecret
  - secretKey: cookieSecret
    remoteRef:
      key: /sec/oauth2proxy
      property: cookieSecret
