apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: oauth2-proxy-config-external-secret
spec:
  refreshPolicy: OnChange
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: oauth2-proxy-config
    manifest:
      apiVersion: v1
      kind: ConfigMap
    template:
      data:
        oauth2_proxy.cfg: |
          cookie_secret = "OQINaROshtE9TcZkNAm-5Zs2Pv3xaWytBmc5W7sPX7w="
          cookie_domains = ".${INFRA_DOMAIN}"
          whitelist_domains = [".${INFRA_DOMAIN}"]

          client_id = "oauth2-proxy"
          client_secret = "{{ .clientSecret }}"
          cookie_secure = false

          redirect_url = "http://oauth2-proxy.${INFRA_DOMAIN}/oauth2/callback"

          upstreams = [ "file:///dev/null" ]

          set_xauthrequest = true
          provider = "oidc"
          oidc_issuer_url = "https://keycloak.${INFRA_DOMAIN}/auth/realms/cluster"
  data:
  - secretKey: clientSecret
    remoteRef:
      key: /sec/keycloak
      property: clientSecret
