apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
- name: oauth2-proxy
  repo: https://oauth2-proxy.github.io/manifests
  version: 10.1.4
  releaseName: oauth2-proxy
  namespace: sec
  valuesFile: values.yaml

resources:
- external-secrets.yaml
- ref-grant.yaml
