apiVersion: gateway.networking.k8s.io/v1beta1
kind: ReferenceGrant
metadata:
  name: allow-ext-auth-from-monitoring
spec:
  from:
  - group: gateway.envoyproxy.io
    kind: SecurityPolicy
    namespace: monitoring
  - group: gateway.envoyproxy.io
    kind: HTTPRoute
    namespace: monitoring
  to:
  - group: ""
    kind: Service
    name: oauth2-proxy
