alphaConfig:
  enabled: true
  existingConfig: oauth2-proxy-config

extraArgs:
  reverse-proxy: true
  redirect-url: "https://oauth2-proxy.${INFRA_DOMAIN}/oauth2/callback"
  cookie-csrf-per-request: true
  cookie-csrf-per-request-limit: 300
  cookie-secure: true
  whitelist-domain: "*.${INFRA_DOMAIN}"
