alphaConfig:
  enabled: true
  existingConfig: oauth2-proxy-config

extraArgs:
  reverse-proxy: true
  redirect-url: "https://oauth2-proxy.${INFRA_DOMAIN}/oauth2/callback"
  cookie-csrf-per-request: true
  cookie-csrf-expire: "5m"
  cookie-name: "_oauth2_proxy"
  cookie-secure: true
  cookie-domain: ".${INFRA_DOMAIN}"
  cookie-httponly: false
  whitelist-domain: ".${INFRA_DOMAIN}"
  set-xauthrequest: true
