apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: p2p

helmGlobals:
  chartHome: ../../charts

helmCharts:
- name: base-app
  releaseName: shelfmark
  valuesFile: values.yaml

resources:
- external-secrets.yaml
