deployment:
  image:
    repository: ghcr.io/calibrain/shelfmark
    tag: "v1.3.3@sha256:1f0e9ecdef24a3d8f5787282eaea3859edcd3bb0c3d508382e2b2bc4bb18d7d6"

vpn:
  image:
    repository: qmcgaw/gluetun
    tag: v3.41.1
