apiVersion: "cilium.io/v2"
kind: CiliumLoadBalancerIPPool
metadata:
  name: gateway-lb-pool
spec:
  blocks:
  - cidr: ${INFRA_LB_IP}/32
---
apiVersion: "cilium.io/v2alpha1"
kind: CiliumL2AnnouncementPolicy
metadata:
  name: lb-policy
spec:
  serviceSelector:
    matchLabels:
      gateway.envoyproxy.io/owning-gateway-name: cluster-gateway
  interfaces:
  - eth0
  externalIPs: true
  loadBalancerIPs: true
