apiVersion: v1
kind: ConfigMap
metadata:
  name: keycloak-config
data:
  cluster-realm.json: |
    {
      "enabled": true,
      "realm": "cluster",
      "users": [
        {
          "username": "admin",
          "email": "admin@mail.de",
          "enabled": true,
          "firstName": "Admin",
          "lastName": "User",
          "credentials": [
            {
              "type": "password",
              "value": "test"
            }
          ]
        }
      ],
      "clients": [
        {
          "clientId": "gateway",
          "name": "gateway",
          "description": "Gateway Client",
          "enabled": true,
          "clientAuthenticatorType": "client-secret",
          "secret": "secret",
          "redirectUris": [
            "https://hubble.${INFRA_DOMAIN}/*"
          ],
          "webOrigins": ["*"]
        }
      ]
    }
