apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: keycloak-admin-credentials-external-secret
spec:
  refreshPolicy: OnChange
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: keycloak-admin-credentials
  data:
  - secretKey: KC_BOOTSTRAP_ADMIN_USERNAME
    remoteRef:
      key: /sec/keycloak
      property: adminUsername
  - secretKey: KC_BOOTSTRAP_ADMIN_PASSWORD
    remoteRef:
      key: /sec/keycloak
      property: adminPassword
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: keycloak-config-external-secret
spec:
  refreshPolicy: OnChange
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: keycloak-config
    manifest:
      apiVersion: v1
      kind: ConfigMap
    template:
      data:
        cluster-realm.json: |
          {
            "enabled": true,
            "realm": "cluster",
            "clientScopeMappings": {
              "gateway": [
                {
                  "clientScope": "gateway-scope",
                  "roles": [
                    "admin",
                    "media"
                  ]
                }
              ]
            },
            "users": [
              {
                "username": "admin",
                "email": "admin@example.com",
                "enabled": true,
                "firstName": "Admin",
                "lastName": "User",
                "credentials": [
                  {
                    "type": "password",
                    "value": "{{ .adminPassword }}"
                  }
                ],
                "clientRoles": {
                  "gateway": [
                    "admin"
                  ]
                }
              }
            ],
            "clients": [
              {
                "clientId": "gateway",
                "name": "gateway",
                "description": "Gateway Client",
                "enabled": true,
                "clientAuthenticatorType": "client-secret",
                "secret": "{{ .clientSecret }}",
                "redirectUris": [
                  "https://hubble.${INFRA_DOMAIN}/*"
                ],
                "webOrigins": ["*"]
              }
            ],
            "roles": {
              "client": {
                "gateway": [
                  {
                    "name": "admin",
                    "clientRole": true
                  },
                  {
                    "name": "media",
                    "clientRole": true
                  }
                ]
              }
            },
            "clientScopes": [
              {
                "name": "gateway-scope",
                "protocol": "openid-connect",
                "attributes": {
                  "include.in.token.scope": "true",
                  "display.on.consent.screen": "true"
                }
              }
            ]
          }
  data:
  - secretKey: adminPassword
    remoteRef:
      key: /sec/keycloak
      property: adminPassword
  - secretKey: clientSecret
    remoteRef:
      key: /sec/keycloak
      property: clientSecret
