apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: keycloak-admin-credentials-external-secret
spec:
  refreshPolicy: OnChange
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: keycloak-admin-credentials
  data:
  - secretKey: KEYCLOAK_ADMIN
    remoteRef:
      key: /sec/keycloak
      property: adminUsername
  - secretKey: KEYCLOAK_ADMIN_PASSWORD
    remoteRef:
      key: /sec/keycloak
      property: adminPassword
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: keycloak-config-external-secret
spec:
  refreshPolicy: OnChange
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: keycloak-config
    manifest:
      apiVersion: v1
      kind: ConfigMap
    template:
      data:
        cluster-realm.json: |
          {
            "enabled": true,
            "realm": "cluster",
            "users": [
              {
                "username": "admin",
                "email": "admin@example.com",
                "enabled": true,
                "firstName": "Admin",
                "lastName": "User",
                "credentials": [
                  {
                    "type": "password",
                    "value": "{{ .adminPassword }}"
                  }
                ]
              }
            ],
            "clients": [
              {
                "clientId": "gateway",
                "name": "gateway",
                "description": "Gateway Client",
                "enabled": true,
                "clientAuthenticatorType": "client-secret",
                "secret": "{{ .clientSecret }}",
                "redirectUris": [
                  "https://hubble.${INFRA_DOMAIN}/*"
                ],
                "webOrigins": ["*"]
              }
            ]
          }
  data:
  - secretKey: adminPassword
    remoteRef:
      key: /sec/keycloak
      property: adminPassword
  - secretKey: clientSecret
    remoteRef:
      key: /sec/keycloak
      property: clientSecret
