apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: keycloak-admin-credentials-external-secret
spec:
  refreshPolicy: OnChange
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: keycloak-admin-credentials
  data:
  - secretKey: KC_BOOTSTRAP_ADMIN_USERNAME
    remoteRef:
      key: /sec/keycloak
      property: adminUsername
  - secretKey: KC_BOOTSTRAP_ADMIN_PASSWORD
    remoteRef:
      key: /sec/keycloak
      property: adminPassword
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: keycloak-config-external-secret
spec:
  refreshPolicy: OnChange
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: keycloak-config
    manifest:
      apiVersion: v1
      kind: ConfigMap
    template:
      data:
        cluster-realm.json: |
          {
            "enabled": true,
            "realm": "cluster",
            "users": [
              {
                "username": "admin",
                "email": "admin@example.com",
                "enabled": true,
                "firstName": "Admin",
                "lastName": "User",
                "emailVerified": true,
                "credentials": [
                  {
                    "type": "password",
                    "value": "{{ .adminPassword }}"
                  }
                ],
                "clientRoles": {
                  "oauth2-proxy": [
                    "admin"
                  ]
                }
              },
              {
                "username": "m.media",
                "email": "m.media@example.com",
                "enabled": true,
                "firstName": "Media",
                "lastName": "User",
                "emailVerified": true,
                "credentials": [
                  {
                    "type": "password",
                    "value": "{{ .mediaPassword }}"
                  }
                ],
                "clientRoles": {
                  "oauth2-proxy": [
                    "media"
                  ]
                }
              }
            ],
            "clients": [
              {
                "clientId": "oauth2-proxy",
                "name": "oauth2-proxy",
                "description": "OAuth2 Proxy Client",
                "enabled": true,
                "clientAuthenticatorType": "client-secret",
                "secret": "{{ .clientSecret }}",
                "redirectUris": [
                  "https://oauth2-proxy.${INFRA_DOMAIN}/oauth2/callback"
                ],
                "webOrigins": ["*"],
                "serviceAccountsEnabled" : true,
                "authorizationServicesEnabled" : true,
                "protocolMappers" : [
                  {
                    "name" : "aud-mapper-oauth2-proxy",
                    "protocol" : "openid-connect",
                    "protocolMapper" : "oidc-audience-mapper",
                    "consentRequired" : false,
                    "config" : {
                      "included.client.audience" : "oauth2-proxy",
                      "id.token.claim" : "true",
                      "lightweight.claim" : "false",
                      "access.token.claim" : "true",
                      "introspection.token.claim" : "true"
                    }
                  }
                ]
              }
            ],
            "clientScopes" : [
              {
                "name" : "profile",
                "protocolMappers" : [
                  {
                    "name" : "roles",
                    "protocol" : "openid-connect",
                    "protocolMapper" : "oidc-usermodel-client-role-mapper",
                    "config" : {
                      "introspection.token.claim" : "true",
                      "multivalued" : "true",
                      "userinfo.token.claim" : "true",
                      "id.token.claim" : "true",
                      "lightweight.claim" : "false",
                      "access.token.claim" : "true",
                      "claim.name" : "roles",
                      "jsonType.label" : "String",
                      "usermodel.clientRoleMapping.clientId" : "oauth2-proxy"
                    }
                  },
                  {
                    "name" : "username",
                    "protocol" : "openid-connect",
                    "protocolMapper" : "oidc-usermodel-attribute-mapper",
                    "config" : {
                      "aggregate.attrs" : "false",
                      "introspection.token.claim" : "true",
                      "multivalued" : "false",
                      "userinfo.token.claim" : "true",
                      "user.attribute" : "username",
                      "id.token.claim" : "true",
                      "lightweight.claim" : "false",
                      "access.token.claim" : "true",
                      "claim.name" : "username",
                      "jsonType.label" : "String"
                    }
                  },
                  {
                    "name" : "email",
                    "protocol" : "openid-connect",
                    "protocolMapper" : "oidc-usermodel-attribute-mapper",
                    "config" : {
                      "introspection.token.claim" : "true",
                      "userinfo.token.claim" : "true",
                      "user.attribute" : "email",
                      "id.token.claim" : "true",
                      "access.token.claim" : "true",
                      "claim.name" : "email",
                      "jsonType.label" : "String"
                    }
                  }
                ]
              }
            ],
            "roles": {
              "client": {
                "oauth2-proxy": [
                  {
                    "name": "admin",
                    "clientRole": true
                  },
                  {
                    "name": "media",
                    "clientRole": true
                  }
                ]
              }
            }
          }
  data:
  - secretKey: adminPassword
    remoteRef:
      key: /sec/keycloak
      property: adminPassword
  - secretKey: mediaPassword
    remoteRef:
      key: /sec/keycloak
      property: mediaPassword
  - secretKey: clientSecret
    remoteRef:
      key: /sec/keycloak
      property: clientSecret
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: keycloak-db-external-secret
spec:
  refreshPolicy: OnChange
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: keycloak-db-secret
    template:
      type: kubernetes.io/basic-auth
      data:
        username: keycloak
        password: "{{ .password }}"
  data:
  - secretKey: password
    remoteRef:
      key: /sec/keycloak
      property: dbPassword
