apiVersion: batch/v1
kind: Job
metadata:
  name: bootstrap
spec:
  template:
    spec:
      containers:
      - name: bootstrap
        image: adorsys/keycloak-config-cli:latest
        env:
        - name: KEYCLOAK_URL
          value: "http://keycloak-keycloakx-http:9000/auth"
        #- name: KEYCLOAK_AVAILABILITYCHECK_ENABLED
        #  value: "true"
        #- name: KEYCLOAK_AVAILABILITYCHECK_TIMEOUT
        #  value: "120s"
        - name: KEYCLOAK_CONNECTTIMEOUT
          value: "120s"
        - name: KEYCLOAK_USER
          valueFrom:
            secretKeyRef:
              name: keycloak-admin-credentials
              key: KEYCLOAK_ADMIN
        - name: KEYCLOAK_PASSWORD
          valueFrom:
            secretKeyRef:
              name: keycloak-admin-credentials
              key: KEYCLOAK_ADMIN_PASSWORD
        volumeMounts:
        - name: config
          mountPath: /config
      restartPolicy: Never
      volumes:
      - name: config
        configMap:
          name: keycloak-config
