apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
- name: keycloakx
  repo: oci://ghcr.io/codecentric/helm-charts
  version: 7.1.8
  releaseName: keycloak
  namespace: sec
  valuesFile: values.yaml

resources:
- external-secret.yaml
- httproute.yaml
