command:
  - "/opt/keycloak/bin/kc.sh"
  - "start"
  - "--http-port=8080"
  - "--hostname=keycloak.${INFRA_DOMAIN}"
  - "--proxy-headers=xforwarded"
  - "--hostname-strict=true"

extraEnv: |
  - name: JAVA_OPTS_APPEND
    value: >-
      -Djgroups.dns.query=keycloak-keycloakx-headless

extraEnvFrom: |
  - secretRef:
      name: keycloak-admin-credentials

extraInitContainers: |
  - name: download-keycloak-config-cli
    image: busybox
    command:
    - sh
    - -c
    - |
      wget -O /keycloak-config-cli/cli.jar https://github.com/adorsys/keycloak-config-cli/releases/download/v6.5.0/keycloak-config-cli-25.0.1.jar
    volumeMounts:
    - name: keycloak-config-cli
      mountPath: /keycloak-config-cli

lifecycleHooks: |
  postStart:
    exec:
      command:
      - /bin/sh
      - -c
      - |
        java -jar /opt/keycloak/lib/keycloak-config-cli.jar \
          --keycloak.url=http://localhost:8080/auth \
          --keycloak.user=${KEYCLOAK_ADMIN} \
          --keycloak.password=${KEYCLOAK_ADMIN_PASSWORD} \
          --keycloak.availability-check.enabled=true \
          --keycloak.availability-check.timeout=120s \
          --keycloak.connect-timeout=120s \
          --import.files.locations=/config/*.json

extraVolumes: |
  - name: keycloak-config-cli
    emptyDir: {}
  - name: config
    configMap:
      name: keycloak-config

extraVolumeMounts: |
  - name: keycloak-config-cli
    mountPath: /opt/keycloak/lib/keycloak-config-cli.jar
    subPath: cli.jar
  - name: config
    mountPath: /config
