command:
  - "/opt/keycloak/bin/kc.sh"
  - "start"
  - "--http-port=8080"
  - "--hostname=https://keycloak.${INFRA_DOMAIN}"
  - "--proxy-headers=xforwarded"
  - "--hostname-strict=false"

extraEnv: |
  - name: JAVA_OPTS_APPEND
    value: >-
      -Djgroups.dns.query=keycloak-keycloakx-headless

extraEnvFrom: |
  - secretRef:
      name: keycloak-admin-credentials
