command:
  - "/opt/keycloak/bin/kc.sh"
  - "start"
  - "--http-port=8080"
  - "--hostname=keycloak.${INFRA_DOMAIN}"
  - "--proxy-headers=xforwarded"
  - "--hostname-strict=true"

dbchecker:
  enabled: true

database:
  existingSecret: keycloak-db-secret
  existingSecretKey: password
  vendor: postgres
  hostname: keycloak-db-rw.sec.svc.cluster.local
  port: 5432
  username: keycloak
  database: keycloak

extraEnv: |
  - name: JAVA_OPTS_APPEND
    value: >-
      -Djgroups.dns.query=keycloak-keycloakx-headless

extraEnvFrom: |
  - secretRef:
      name: keycloak-admin-credentials

extraContainers: |
  - name: bootstrap
    image: adorsys/keycloak-config-cli:latest
    env:
      - name: KEYCLOAK_URL
        value: "http://localhost:9000"
      - name: KEYCLOAK_USER
        valueFrom:
          secretKeyRef:
            name: keycloak-admin-credentials
            key: KC_BOOTSTRAP_ADMIN_USERNAME
      - name: KEYCLOAK_PASSWORD
        valueFrom:
          secretKeyRef:
            name: keycloak-admin-credentials
            key: KC_BOOTSTRAP_ADMIN_PASSWORD
    volumeMounts:
      - name: config
        mountPath: /config

extraVolumes: |
  - name: config
    configMap:
      name: keycloak-config
