apiVersion: v1
kind: ConfigMap
metadata:
  name: infra-envsubst-config
  namespace: devops-tools
data:
  plugin.yaml: |
    apiVersion: argoproj.io/v1alpha1
    kind: ConfigManagementPlugin
    metadata:
      name: infra-envsubst
    spec:
      discover:
        find:
          command: [sh, -c, find . -name kustomization.yaml]
      generate:
        command:
        - bash
        - -c
        - |
          set -e

          echo "Replacing env vars in manifests" >&2
          if [[ -f kustomization.yaml ]]; then
            kustomize build . --enable-helm | envsubst '${INFRA_ENV} ${INFRA_DOMAIN} ${INFRA_K8S_NFS} ${INFRA_DATA_NFS} ${INFRA_LB_IP} ${INFRA_LETS_ENCRYPT_EMAIL}'
          else
            echo "[!] Error during infra variables substitution" >&2
            exit 1
          fi
