apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: argocd-external-secret
  namespace: devops-tools
spec:
  refreshPolicy: OnChange
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: argocd-secret
    template:
      data:
        server.secretkey: ""
        admin.password: "{{ .argocdServerAdminPassword }}"
        admin.passwordMtime: "2026-02-10T13:32:47CET"
      metadata:
        labels:
          app.kubernetes.io/name: argocd-secret
          app.kubernetes.io/part-of: argocd
  data:
  - secretKey: argocdServerAdminPassword
    remoteRef:
      key: /devopstools/argocd
      property: admin_password
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: infra-config-external-secret
  namespace: devops-tools
spec:
  refreshPolicy: OnChange
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: infra-config
    manifest:
      apiVersion: v1
      kind: ConfigMap
  data:
  - secretKey: INFRA_ENV
    remoteRef:
      key: /infra
      property: env
  - secretKey: INFRA_DOMAIN
    remoteRef:
      key: /infra
      property: domain
  - secretKey: INFRA_LB_IP
    remoteRef:
      key: /infra
      property: lb_ip
  - secretKey: INFRA_HA_VIP
    remoteRef:
      key: /infra
      property: ha_vip
  - secretKey: INFRA_LETS_ENCRYPT_EMAIL
    remoteRef:
      key: /infra
      property: lets_encrypt_email
