apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: argocd-external-secret
  namespace: devops-tools
spec:
  refreshInterval: 1h0m0s
  secretStoreRef:
    name: vault-secretstore
    kind: ClusterSecretStore
  target:
    name: argocd-secret
    template:
      data:
        server.secretkey: ""
        admin.password: "{{ `{{ .argocdServerAdminPassword }}` }}"
        admin.passwordMtime: "2026-02-10T13:32:47CET"
      metadata:
        labels:
          app.kubernetes.io/name: argocd-secret
          app.kubernetes.io/part-of: argocd
  data:
  - secretKey: argocdServerAdminPassword
    remoteRef:
      key: /devopstools/argocd
      property: admin_password
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: argocd-gh-org-external-secret
  namespace: devops-tools
spec:
  refreshInterval: 1h0m0s
  secretStoreRef:
    name: vault-secretstore
    kind: ClusterSecretStore
  target:
    name: argocd-gh-org-secret
    template:
      data:
        url: https://github.com/argoproj
        type: git
        username: "{{ `{{ .gh_org_username }}` }}"
        password: "{{ `{{ .gh_org_password }}` }}"
      metadata:
        labels:
          argocd.argoproj.io/secret-type: repo-creds
  data:
  - secretKey: gh_org_username
    remoteRef:
      key: /devopstools/argocd
      property: gh_org1_username
  - secretKey: gh_org_password
    remoteRef:
      key: /devopstools/argocd
      property: gh_org1_password
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: infra-config-external-secret
  namespace: devops-tools
spec:
  refreshInterval: 1h0m0s
  secretStoreRef:
    name: vault-secretstore
    kind: ClusterSecretStore
  target:
    name: infra-config
    manifest:
      apiVersion: v1
      kind: ConfigMap
  data:
  - secretKey: INFRA_ENV
    remoteRef:
      key: /infra
      property: env
  - secretKey: INFRA_DOMAIN
    remoteRef:
      key: /infra
      property: domain
  - secretKey: INFRA_K8S_NFS
    remoteRef:
      key: /infra
      property: k8s_nfs
  - secretKey: INFRA_DATA_NFS
    remoteRef:
      key: /infra
      property: data_nfs
  - secretKey: INFRA_LB_IP
    remoteRef:
      key: /infra
      property: lb_ip
