#!/bin/bash

# Verify requirements
verify_requirements() {
  local project_dir=""
  project_dir="$1"

  if ! which kubectl 2>&1 > /dev/null; then
    echo "    [!] kubect not detected!"
    error="1"
  fi

  if ! which helm 2>&1 > /dev/null; then
    echo "    [!] helm not detected!"
    error="1"
  fi

  if [[ $error ]]; then
    exit 1
  fi
}

vault_secrets="$1"
vault_secret_files="$2"

project_path="$(dirname $0)/.."

echo "[+] Verifying requirements..."
verify_requirements "${project_path}"
echo -e "    Everything ready!\\n"

# Install traefik crds
kubectl apply -f https://raw.githubusercontent.com/traefik/traefik/v3.6/docs/content/reference/dynamic-configuration/kubernetes-crd-definition-v1.yml

# Install gateway crds
kubectl apply --server-side -f https://github.com/kubernetes-sigs/gateway-api/releases/download/v1.4.1/standard-install.yaml

# Install storage
echo "[1/5] Bootstraping storage..."
"${project_path}"/default/tooling/bootstrap
echo -e "   Storage ready!\\n"

# Install Vault
echo "[2/5] Bootstraping vault..."
"${project_path}"/vault/tooling/bootstrap "${vault_secrets}" "${vault_secret_files}"
echo -e "   Vault ready!\\n"

# Install ESO
echo "[3/5] Bootstraping ESO..."
"${project_path}"/external-secrets/tooling/bootstrap
echo -e "   ESO ready!\\n"

echo "[4/5] Bootstraping Vault unsealer..."
"${project_path}"/vault/tooling/bootstrap-unsealer
echo -e "   Unsealer ready!\\n"

# Install ArgoCD
echo "[5/5] Bootstraping ArgoCD..."
"${project_path}"/devops-tools/tooling/bootstrap
echo -e "   Devops-tools ready!\\n"

echo "[+] Cluster services ready!"
